# Generated by Django 5.1.2 on 2024-10-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('interests', models.TextField()),
                ('skills', models.TextField()),
                ('personality', models.TextField()),
                ('current_job', models.CharField(max_length=100)),
                ('job_satisfaction', models.IntegerField()),
                ('use_for_training', models.BooleanField(default=False)),
            ],
        ),
    ]
