# Generated by Django 5.1.2 on 2024-10-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_skill_alter_dreamjob_job_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='personalityprofile',
            name='interests',
        ),
        migrations.AddField(
            model_name='personalityprofile',
            name='interests',
            field=models.ManyToManyField(to='recommendations.interest'),
        ),
    ]
