# Generated by Django 5.1.2 on 2024-11-01 05:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0006_fun_remove_personalityprofile_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dreamjob',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
